# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.3

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.3.0/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.3.0/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/lucas/Dropbox/Hobby/temp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/lucas/Dropbox/Hobby/temp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.3.0/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.3.0/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/lucas/Dropbox/Hobby/temp/CMakeFiles /Users/lucas/Dropbox/Hobby/temp/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/lucas/Dropbox/Hobby/temp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CHIP8_emu

# Build rule for target.
CHIP8_emu: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CHIP8_emu
.PHONY : CHIP8_emu

# fast build rule for target.
CHIP8_emu/fast:
	$(MAKE) -f CMakeFiles/CHIP8_emu.dir/build.make CMakeFiles/CHIP8_emu.dir/build
.PHONY : CHIP8_emu/fast

Emulator.o: Emulator.cpp.o

.PHONY : Emulator.o

# target to build an object file
Emulator.cpp.o:
	$(MAKE) -f CMakeFiles/CHIP8_emu.dir/build.make CMakeFiles/CHIP8_emu.dir/Emulator.cpp.o
.PHONY : Emulator.cpp.o

Emulator.i: Emulator.cpp.i

.PHONY : Emulator.i

# target to preprocess a source file
Emulator.cpp.i:
	$(MAKE) -f CMakeFiles/CHIP8_emu.dir/build.make CMakeFiles/CHIP8_emu.dir/Emulator.cpp.i
.PHONY : Emulator.cpp.i

Emulator.s: Emulator.cpp.s

.PHONY : Emulator.s

# target to generate assembly for a file
Emulator.cpp.s:
	$(MAKE) -f CMakeFiles/CHIP8_emu.dir/build.make CMakeFiles/CHIP8_emu.dir/Emulator.cpp.s
.PHONY : Emulator.cpp.s

GameScreen.o: GameScreen.cpp.o

.PHONY : GameScreen.o

# target to build an object file
GameScreen.cpp.o:
	$(MAKE) -f CMakeFiles/CHIP8_emu.dir/build.make CMakeFiles/CHIP8_emu.dir/GameScreen.cpp.o
.PHONY : GameScreen.cpp.o

GameScreen.i: GameScreen.cpp.i

.PHONY : GameScreen.i

# target to preprocess a source file
GameScreen.cpp.i:
	$(MAKE) -f CMakeFiles/CHIP8_emu.dir/build.make CMakeFiles/CHIP8_emu.dir/GameScreen.cpp.i
.PHONY : GameScreen.cpp.i

GameScreen.s: GameScreen.cpp.s

.PHONY : GameScreen.s

# target to generate assembly for a file
GameScreen.cpp.s:
	$(MAKE) -f CMakeFiles/CHIP8_emu.dir/build.make CMakeFiles/CHIP8_emu.dir/GameScreen.cpp.s
.PHONY : GameScreen.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/CHIP8_emu.dir/build.make CMakeFiles/CHIP8_emu.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/CHIP8_emu.dir/build.make CMakeFiles/CHIP8_emu.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/CHIP8_emu.dir/build.make CMakeFiles/CHIP8_emu.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... CHIP8_emu"
	@echo "... Emulator.o"
	@echo "... Emulator.i"
	@echo "... Emulator.s"
	@echo "... GameScreen.o"
	@echo "... GameScreen.i"
	@echo "... GameScreen.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

